networks:
  social-network-service-nw:
    name: social-network-service-nw
    driver: bridge
  interservice-nw:
    name: interservice-nw
    driver: bridge

services:
  backend:
    container_name: social-network-service-backend
    image: social-network-service:0.2.0
    build:
      context: ./
      dockerfile: service.Dockerfile
    networks:
      - social-network-service-nw
      - interservice-nw
    ports:
      - "8080:8080"
      - "8081:8081"
      - "2112:2112"
    command: /app/server --config /app/dev.yml
