name: "social-network-service"

networks:
  social-network-service-nw:
    name: social-network-service-nw
    driver: bridge
  interservice-nw:
    name: interservice-nw
    driver: bridge
  proxy-nw:
    name: proxy-nw
    driver: bridge

services:
  backend:
    image: social-network-service:0.3.0
    build:
      context: ./
      dockerfile: service.Dockerfile
    deploy:
      replicas: 3
    networks:
      - social-network-service-nw
      - interservice-nw
      - proxy-nw
    # ports:
    #   - "8080:8080"
    #   - "8081:8081"
    #   - "2112:2112"
    command: /app/server --config /app/dev.yml

  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    image: nginx:1.27.0-alpine
    networks:
      - proxy-nw
    ports:
      - "80:80"
      # - "8081:8081"
      # - "2112:2112"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
