version: "3.3"

networks:
  otus-hl:
    driver: bridge

services:
  backend:
    container_name: backend
    image: social-network-service
    build:
      context: ./
      dockerfile: service.Dockerfile
    networks:
      - otus-hl
    ports:
      - "8080:8080"
