networks:
  otus-hl:
    driver: bridge

services:
  backend:
    container_name: backend
    image: social-network-service
    build:
      context: ./
      dockerfile: service.Dockerfile
    networks:
      - otus-hl
    ports:
      - "8080:8080"
      - "8081:8081"
      - "2112:2112"
    command: /app/server --config /app/dev.yml --use-tarantool
