name: "social-network-service"

networks:
  social-network-service-nw:
    name: social-network-service-nw
    driver: bridge

services:
  etcd0:
    container_name: "${COMPOSE_PROJECT_NAME}-etcd0"
    image: quay.io/coreos/etcd:v2.3.8
    networks:
      - social-network-service-nw
    command:
      [
        "--name", "etcd0",
        "--data-dir", "/etcd-data",
        "--listen-client-urls", "http://0.0.0.0:2379",
        "--advertise-client-urls", "http://${COMPOSE_PROJECT_NAME}-etcd0:2379",
        "--listen-peer-urls", "http://0.0.0.0:2380",
        "--initial-advertise-peer-urls", "http://etcd0:2380",
        "--initial-cluster", "etcd0=http://${COMPOSE_PROJECT_NAME}-etcd0:2380,etcd1=http://${COMPOSE_PROJECT_NAME}-etcd1:2380,etcd2=http://${COMPOSE_PROJECT_NAME}-etcd2:2380",
        "--initial-cluster-token", "token",
        "--initial-cluster-state", "new"
      ]

  etcd1:
    container_name: "${COMPOSE_PROJECT_NAME}-etcd1"
    image: quay.io/coreos/etcd:v2.3.8
    networks:
      - social-network-service-nw
    command:
      [
        "--name", "etcd1",
        "--data-dir", "/etcd-data",
        "--listen-client-urls", "http://0.0.0.0:2379",
        "--advertise-client-urls", "http://${COMPOSE_PROJECT_NAME}-etcd1:2379",
        "--listen-peer-urls", "http://0.0.0.0:2380",
        "--initial-advertise-peer-urls", "http://${COMPOSE_PROJECT_NAME}-etcd1:2380",
        "--initial-cluster", "etcd0=http://${COMPOSE_PROJECT_NAME}-etcd0:2380,etcd1=http://${COMPOSE_PROJECT_NAME}-etcd1:2380,etcd2=http://${COMPOSE_PROJECT_NAME}-etcd2:2380",
        "--initial-cluster-token", "token",
        "--initial-cluster-state", "new"
      ]

  etcd2:
    container_name: "${COMPOSE_PROJECT_NAME}-etcd2"
    image: quay.io/coreos/etcd:v2.3.8
    networks:
      - social-network-service-nw
    command:
      [
        "--name", "etcd2",
        "--data-dir", "/etcd-data",
        "--listen-client-urls", "http://0.0.0.0:2379",
        "--advertise-client-urls", "http://${COMPOSE_PROJECT_NAME}-etcd2:2379",
        "--listen-peer-urls", "http://0.0.0.0:2380",
        "--initial-advertise-peer-urls", "http://${COMPOSE_PROJECT_NAME}-etcd2:2380",
        "--initial-cluster", "etcd0=http://${COMPOSE_PROJECT_NAME}-etcd0:2380,etcd1=http://${COMPOSE_PROJECT_NAME}-etcd1:2380,etcd2=http://${COMPOSE_PROJECT_NAME}-etcd2:2380",
        "--initial-cluster-token", "token",
        "--initial-cluster-state", "new"
      ]

  postgres0:
    container_name: "${COMPOSE_PROJECT_NAME}-postgres0"
    image: ghcr.io/zalando/spilo-16:3.2-p2
    networks:
      - social-network-service-nw
    environment:
      ETCD_HOST: ${COMPOSE_PROJECT_NAME}-etcd0:2379
      ETCD_HOSTS: ${COMPOSE_PROJECT_NAME}-etcd0:2379,${COMPOSE_PROJECT_NAME}-etcd1:2379,${COMPOSE_PROJECT_NAME}-etcd2:2379
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: 123
      ALLOW_NOSSL: true
      PGVERSION: 16
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started

  postgres1:
    container_name: "${COMPOSE_PROJECT_NAME}-postgres1"
    image: ghcr.io/zalando/spilo-16:3.2-p2
    networks:
      - social-network-service-nw
    environment:
      ETCD_HOST: ${COMPOSE_PROJECT_NAME}-etcd0:2379
      ETCD_HOSTS: ${COMPOSE_PROJECT_NAME}-etcd0:2379,${COMPOSE_PROJECT_NAME}-etcd1:2379,${COMPOSE_PROJECT_NAME}-etcd2:2379
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: 123
      ALLOW_NOSSL: true
      PGVERSION: 16
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started

  postgres2:
    container_name: "${COMPOSE_PROJECT_NAME}-postgres2"
    image: ghcr.io/zalando/spilo-16:3.2-p2
    networks:
      - social-network-service-nw
    environment:
      ETCD_HOST: ${COMPOSE_PROJECT_NAME}-etcd0:2379
      ETCD_HOSTS: ${COMPOSE_PROJECT_NAME}-etcd0:2379,${COMPOSE_PROJECT_NAME}-etcd1:2379,${COMPOSE_PROJECT_NAME}-etcd2:2379
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: 123
      ALLOW_NOSSL: true
      PGVERSION: 16
    depends_on:
      etcd0:
        condition: service_started
      etcd1:
        condition: service_started
      etcd2:
        condition: service_started

  haproxy:
    container_name: "${COMPOSE_PROJECT_NAME}-haproxy"
    image: social-newtwok-service-haproxy:0.2.0
    build:
      context: ./
      dockerfile: haproxy.Dockerfile
    networks:
      - social-network-service-nw
    ports:
      - "7000:7000"
      - "15432:15432"
      - "15433:25432"
      - "15434:35432"
    depends_on:
      postgres0:
        condition: service_started
      postgres1:
        condition: service_started
      postgres2:
        condition: service_started

  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis
    networks:
      - social-network-service-nw
    ports:
      - "16379:6379"
