version: '3'

tasks:
  run:
    desc: Run the service
    cmds:
      - go run ./cmd/app/main.go --config ./configs/local.yml

  gen-pb:
    desc: Generate *.pb.go files
    cmds:
      - protoc --proto_path ./proto --go_out ./internal/grpc/dialogue/ --go_opt paths=source_relative --go-grpc_out ./internal/grpc/dialogue/ --go-grpc_opt paths=source_relative ./proto/dialogue.proto
      - protoc --proto_path ./proto --go_out ./internal/grpc/counter/ --go_opt paths=source_relative --go-grpc_out ./internal/grpc/counter/ --go-grpc_opt paths=source_relative ./proto/counter.proto

  gen-profiles:
    desc: Generate random profiles
    summary: |
      Generate random profiles.

      Supported flags:
      --count       Number of accounts to be created
      --batch-size  Size of batches

      Usage:
      task gen-profiles -- --count 1000 --batch-size 50
    cmds:
      - go run ./cmd/gen-profiles/main.go {{.CLI_ARGS}}

  sim:
    desc: Run activity simulation
    cmds:
      - go run ./cmd/sim/main.go 10 ./scripts/

  compose-service-up:
    desc: Up the container of the service
    cmds:
      - docker compose -f ./docker-compose-service.yml up -d

  compose-service-down:
    desc: Down the container of the service
    cmds:
      - docker compose -f ./docker-compose-service.yml down

  compose-infra-up:
    desc: Up infrastructure containers
    cmds:
      - docker compose -f ./docker-compose-infra.yml up -d

  compose-infra-down:
    desc: Down infrastructure containers
    cmds:
      - docker compose -f ./docker-compose-infra.yml down

  migrate-up:
    desc: Migrate database up
    cmds:
      - goose -dir ./migrations/ postgres "host=localhost port=15432 user=postgres password=123 dbname=social_network_db" up

  migrate-down:
    desc: Migrate database down
    cmds:
      - goose -dir ./migrations/ postgres "host=localhost port=15432 user=postgres password=123 dbname=social_network_db" down

  gen-swag:
    desc: Generate Swagger
    cmds:
      - swag init -g ./internal/app/app.go
