version: '3'

tasks:
  run:
    desc: Run the service
    cmds:
      - go run ./cmd/app/main.go {{.CLI_ARGS}}

  gen-profiles:
    desc: Generate random profiles
    summary: |
      Generate random profiles.

      Supported flags:
      --count       Number of accounts to be created
      --batch-size  Size of batches

      Usage:
      task gen-profiles -- --count 1000 --batch-size 50
    cmds:
      - go run ./cmd/gen-profiles/main.go {{.CLI_ARGS}}

  sim:
    desc: Run activity simulation
    cmds:
      - go run ./cmd/sim/main.go 10 ./scripts/

  compose-service-up:
    desc: Up the container of the service
    cmds:
      - docker compose -f ./docker-compose-service.yml up -d

  compose-service-down:
    desc: Down the container of the service
    cmds:
      - docker compose -f ./docker-compose-service.yml down

  compose-infra-up:
    desc: Up infrastructure containers
    cmds:
      - docker compose -f ./docker-compose-infra.yml up -d

  compose-infra-down:
    desc: Down infrastructure containers
    cmds:
      - docker compose -f ./docker-compose-infra.yml down

  migrate-up:
    desc: Migrate database up
    cmds:
      - goose -dir ./migrations/social_network_db/ postgres "host=localhost port=15432 user=postgres password=123 dbname=social_network_db" up

  migrate-down:
    desc: Migrate database down
    cmds:
      - goose -dir ./migrations/social_network_db/ postgres "host=localhost port=15432 user=postgres password=123 dbname=social_network_db" down

  migrate-shards-up:
    desc: Migrate sharded database up
    cmds:
      - goose -dir ./migrations/dialogues_db/ postgres "host=localhost port=5432 user=postgres dbname=postgres" up

  migrate-shards-down:
    desc: Migrate sharded database down
    cmds:
      - goose -dir ./migrations/dialogues_db/ postgres "host=localhost port=5432 user=postgres dbname=postgres" down

  gen-swag:
    desc: Generate Swagger
    cmds:
      - swag init -g ./internal/app/app.go
