kafka_brokers:
  - kafka1:29091
  - kafka2:29092
  - kafka3:29093

producers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

consumers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

database:
  host: "haproxy"
  master_port: 15432
  sync_port: 25432
  async_port: 35432

  user: "postgres"
  password: "123"
  dbname: social_network_db

redis:
  connection_string: "redis:6379"
