kafka_brokers:
  - localhost:9091
  - localhost:9092
  - localhost:9093

producers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

consumers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

database:
  host: "haproxy"
  master_port: 15432
  sync_port: 25432
  async_port: 35432

  user: "postgres"
  password: "123"
  dbname: social_network_db

redis:
  connection_string: "localhost:6379"
