service:
  http_port: 8080
  websocket_port: 8081
  metrics_port: 2112

kafka:
  brokers:
    - kafka1:29091
    - kafka2:29092
    - kafka3:29093
  producers:
    posts:
      topic: "post_events"
    feed:
      topic: "feed_cache_commands"
  consumers:
    posts:
      topic: "post_events"
    feed:
      topic: "feed_cache_commands"

database:
  host: "social-network-service-haproxy"
  master_port: 15432
  sync_port: 25432
  async_port: 35432
  dbname: "social_network_db"
  user: "postgres"
  password: "123"

redis:
  connection_string: "social-network-service-redis:6379"

grpc_clients:
  dialogue_service_addr: "dialogue-service-backend:8084"
  counter_service_addr: "counter-service-backend:8084"
