kafka_brokers:
  - social-network-service-kafka1:29091
  - social-network-service-kafka2:29092
  - social-network-service-kafka3:29093

producers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

consumers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

grpc_clients:
  dialogue_service_addr: "dialogue-service-backend:8084"

database:
  host: "social-network-service-haproxy"
  master_port: 15432
  sync_port: 25432
  async_port: 35432
  dbname: "social_network_db"
  user: "postgres"
  password: "123"

sharded_database:
  host: "social-network-service-master"
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: ""

redis:
  connection_string: "social-network-service-redis:6379"
