kafka_brokers:
  - localhost:9091
  - localhost:9092
  - localhost:9093

producers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

consumers:
  posts:
    topic: "post_events"
  feed:
    topic: "feed_cache_commands"

database:
  host: "localhost"
  master_port: 15432
  sync_port: 25432
  async_port: 35432
  dbname: "social_network_db"
  user: "postgres"
  password: "123"

sharded_database:
  host: "localhost"
  port: 5432
  dbname: "postgres"
  user: "postgres"
  password: ""

redis:
  connection_string: "localhost:6379"
