// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: dialogue.proto

package dialogue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMessagesV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserId string `protobuf:"bytes,1,opt,name=FromUserId,proto3" json:"FromUserId,omitempty"`
	ToUserId   string `protobuf:"bytes,2,opt,name=ToUserId,proto3" json:"ToUserId,omitempty"`
}

func (x *GetMessagesV1Request) Reset() {
	*x = GetMessagesV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogue_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessagesV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesV1Request) ProtoMessage() {}

func (x *GetMessagesV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_dialogue_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesV1Request.ProtoReflect.Descriptor instead.
func (*GetMessagesV1Request) Descriptor() ([]byte, []int) {
	return file_dialogue_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessagesV1Request) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *GetMessagesV1Request) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

type GetMessagesV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*GetMessagesV1Response_Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *GetMessagesV1Response) Reset() {
	*x = GetMessagesV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogue_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessagesV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesV1Response) ProtoMessage() {}

func (x *GetMessagesV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_dialogue_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesV1Response.ProtoReflect.Descriptor instead.
func (*GetMessagesV1Response) Descriptor() ([]byte, []int) {
	return file_dialogue_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessagesV1Response) GetMessages() []*GetMessagesV1Response_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserId string `protobuf:"bytes,1,opt,name=FromUserId,proto3" json:"FromUserId,omitempty"`
	ToUserId   string `protobuf:"bytes,2,opt,name=ToUserId,proto3" json:"ToUserId,omitempty"`
	Text       string `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *SendMessageV1Request) Reset() {
	*x = SendMessageV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogue_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageV1Request) ProtoMessage() {}

func (x *SendMessageV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_dialogue_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageV1Request.ProtoReflect.Descriptor instead.
func (*SendMessageV1Request) Descriptor() ([]byte, []int) {
	return file_dialogue_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageV1Request) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SendMessageV1Request) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SendMessageV1Request) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMessageV1Response) Reset() {
	*x = SendMessageV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogue_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageV1Response) ProtoMessage() {}

func (x *SendMessageV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_dialogue_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageV1Response.ProtoReflect.Descriptor instead.
func (*SendMessageV1Response) Descriptor() ([]byte, []int) {
	return file_dialogue_proto_rawDescGZIP(), []int{3}
}

type GetMessagesV1Response_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserId string `protobuf:"bytes,1,opt,name=FromUserId,proto3" json:"FromUserId,omitempty"`
	ToUserId   string `protobuf:"bytes,2,opt,name=ToUserId,proto3" json:"ToUserId,omitempty"`
	Text       string `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *GetMessagesV1Response_Message) Reset() {
	*x = GetMessagesV1Response_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dialogue_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessagesV1Response_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesV1Response_Message) ProtoMessage() {}

func (x *GetMessagesV1Response_Message) ProtoReflect() protoreflect.Message {
	mi := &file_dialogue_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesV1Response_Message.ProtoReflect.Descriptor instead.
func (*GetMessagesV1Response_Message) Descriptor() ([]byte, []int) {
	return file_dialogue_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetMessagesV1Response_Message) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *GetMessagesV1Response_Message) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *GetMessagesV1Response_Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_dialogue_proto protoreflect.FileDescriptor

var file_dialogue_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x22, 0x52, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb7,
	0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x64, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x59, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72,
	0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x6f, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x22, 0x66, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74,
	0x22, 0x17, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb5, 0x01, 0x0a, 0x0f, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x56, 0x31, 0x12, 0x1e,
	0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x50, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x31,
	0x12, 0x1e, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x72, 0x6f, 0x63, 0x68, 0x69, 0x2d, 0x6b, 0x65, 0x79, 0x64, 0x72, 0x65, 0x61, 0x6d, 0x2f,
	0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x75, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dialogue_proto_rawDescOnce sync.Once
	file_dialogue_proto_rawDescData = file_dialogue_proto_rawDesc
)

func file_dialogue_proto_rawDescGZIP() []byte {
	file_dialogue_proto_rawDescOnce.Do(func() {
		file_dialogue_proto_rawDescData = protoimpl.X.CompressGZIP(file_dialogue_proto_rawDescData)
	})
	return file_dialogue_proto_rawDescData
}

var file_dialogue_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dialogue_proto_goTypes = []interface{}{
	(*GetMessagesV1Request)(nil),          // 0: dialogue.GetMessagesV1Request
	(*GetMessagesV1Response)(nil),         // 1: dialogue.GetMessagesV1Response
	(*SendMessageV1Request)(nil),          // 2: dialogue.SendMessageV1Request
	(*SendMessageV1Response)(nil),         // 3: dialogue.SendMessageV1Response
	(*GetMessagesV1Response_Message)(nil), // 4: dialogue.GetMessagesV1Response.Message
}
var file_dialogue_proto_depIdxs = []int32{
	4, // 0: dialogue.GetMessagesV1Response.messages:type_name -> dialogue.GetMessagesV1Response.Message
	0, // 1: dialogue.DialogueService.GetMessagesV1:input_type -> dialogue.GetMessagesV1Request
	2, // 2: dialogue.DialogueService.SendMessageV1:input_type -> dialogue.SendMessageV1Request
	1, // 3: dialogue.DialogueService.GetMessagesV1:output_type -> dialogue.GetMessagesV1Response
	3, // 4: dialogue.DialogueService.SendMessageV1:output_type -> dialogue.SendMessageV1Response
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dialogue_proto_init() }
func file_dialogue_proto_init() {
	if File_dialogue_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dialogue_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessagesV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogue_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessagesV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogue_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogue_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dialogue_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessagesV1Response_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dialogue_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dialogue_proto_goTypes,
		DependencyIndexes: file_dialogue_proto_depIdxs,
		MessageInfos:      file_dialogue_proto_msgTypes,
	}.Build()
	File_dialogue_proto = out.File
	file_dialogue_proto_rawDesc = nil
	file_dialogue_proto_goTypes = nil
	file_dialogue_proto_depIdxs = nil
}
